name: CI

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Install Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install package
        run: uv sync --all-extras

      - name: Run tests
        run: ./scripts/test

      - name: Check for lint
        run: ./scripts/lint
