name: Publish STAC Extension JSON Schema
on:
  push:
    tags:
      - "extension-v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Inject env variables
        uses: rlespinasse/github-slug-action@v4.4.1
      - uses: actions/checkout@v4
      - name: Parse extension version
        run: |
          extension_version=$(echo "$env.GITHUB_REF_SLUG" | sed 's/extension-//')
          echo "EXTENSION_VERSION=${extension_version}" >> $GITHUB_ENV
      - name: deploy JSON Schema for version ${{ env.EXTENSION_VERSION }}
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: json-schema
          destination_dir: ${{ env.EXTENSION_VERSION }}
