name: Publish STAC Extension JSON Schema
on:
  push:
    tags:
      - "extension-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse extension version
        id: prep
        run: |
          extension_version=$(echo ${{ env.GITHUB_REF }}" | awk -F '/' '{ print $NF }' | sed 's/extension-//')
          echo "EXTENSION_VERSION=${extension_version}" >> $GITHUB_ENV

      - name: Build GH Pages static files
        id: build
        run: |
          site=site/oam/${EXTENSION_VERSION}
          mkdir -p $site
          cp stac-extension/json-schema/schema.json $site/schema.json
          # sigh - force Github Actions "upload-artifact" to keep directory structure
          # ref: https://github.com/actions/upload-artifact/issues/174
          touch site/.gitignore

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
